// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // It's crucial to have valid web configurations if you plan to run on web.
      // Since they are empty, we throw an error to avoid silent failures.
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure` to generate them.',
      );
    }
    // This switch statement is now robust for supported platforms.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'run `flutterfire configure` to generate them.',
        );
      case TargetPlatform.windows:
        // Fallback to Android options for Windows.
        return android;
      case TargetPlatform.linux:
        // Fallback to Android options for Linux.
        return android;
      case TargetPlatform.fuchsia:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for Fuchsia.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKueErj1mUOBDCjPZD9tEyM7Kf7iNfwI',
    appId: '1:331553349621:android:c3e96655b1063283430abc',
    messagingSenderId: '331553349621',
    projectId: 'vanmarket-50d9d',
    storageBucket: 'vanmarket-50d9d.appspot.com',
  );

  // WARNING: These are copied from Android for build purposes.
  // You should re-run `flutterfire configure` to get correct iOS values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKueErj1mUOBDCjPZD9tEyM7Kf7iNfwI', // Using Android API Key as a fallback
    appId: '1:331553349621:ios:YOUR_IOS_APP_ID_SUFFIX', // Placeholder - MUST be replaced
    messagingSenderId: '331553349621',
    projectId: 'vanmarket-50d9d',
    storageBucket: 'vanmarket-50d9d.appspot.com', // Corrected bucket name
    iosBundleId: 'com.example.myapp', // Placeholder - MUST match your Xcode bundle ID
  );
}
